### ISSUE TITLE
Make it work on Windows - partial workaround provided

### ISSUE THREAD

**Issue by brudo** [sanderhahn/multipass-hosts#1]
On Windows, the hosts file is in C:\Windows\system32\drivers\etc\hosts instead of simply /etc/hosts as on Linux.

To work around this difference and make it work without modifying the code, I added a junction link as follows:

`mklink /J C:\etc C:\Windows\System32\drivers\etc`

Then, if I run multipass-hosts as administrator, from the C: drive, my hosts file is found and updated successfully.

This workaround does require that the script be executed from the same drive where the link was created, and it leaves that "etc" link at the root of the C: drive for all to see. Also, it assumes an NTFS file system to support Junction Links.

A workaround like this would not be needed, if the script is amended to detect Windows and look in the correct location in lieu of /etc/hosts. This could look something like the following (untested), to be called in lieu of referencing the constant hostsFile.

```
func getHostsFile() string {
  if runtime.GOOS == "windows" {
    string winDir = os.Getenv("WinDir")
    if len(winDir) > 0 {
      return strings.Replace(winDir, '\\', '/') + '/system32/drivers/etc/hosts'
    }
  }
  return '/etc/hosts'
}


```

**Comment by sanderhahn** [comment]
Think its a nice idea to have it also working on Windows. Have added some files that should make it work. Can you try it out?

**Comment by brudo** [comment]
Yes, that version worked without requiring the junction link; thank you!

I had to remove the original block by hand, as the end-of-line changed on the start / end markers for the block. Note, it does assume Windows is installed on the C: drive, which will hold true in most but not all cases. It does avoid having to look up windir from the environment as I did in that getHostsFile() function. In a worst case the user could still create a junction link from C:\Windows to the correct location.

**Comment by sanderhahn** [comment]
Yes you are absolutely right and even different versions of Windows can have different system folders. Have replaced it now using the `SystemRoot` environment variable as I understand that it is read-only and serves the same purpose. Thank you for your feedback and the example code :-)
